version: 2.1
environment:
  AWS_ACCESS_KEY_ID: ASIAQU62E6EGWJSARNFO
  AWS_SECRET_ACCESS_KEY: UDJR1X5Fe0L1HL67wbhTuEryuCin3XsZNOuz1+zB
orbs:
  node: circleci/node@5.0.3
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build:
    stage: dist
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: npm install
      - run:
          name: Build app
          command: npm run build
    artifacts:
    paths:
      - dist/
  deploy:
    docker:
      - image: circleci/node:12.9.1-browsers
        dependencies:
        - dist
    steps:
      - checkout
      - aws-s3/sync:
          from: dist
          to: s3://devops-grupo-8-bucket-prod/

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



