version: 2.1

environment:
  AWS_ACCESS_KEY_ID: ASIAQU62E6EGWJSARNFO
  AWS_SECRET_ACCESS_KEY: UDJR1X5Fe0L1HL67wbhTuEryuCin3XsZNOuz1+zB
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build-test-deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Run Tests
          command: npm test

      - aws-s3/sync:
          from: dist/
          to: s3://devops-grupo-8-bucket-prod/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test-deploy