version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Build de la App
          command: npm run build

  deploy:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Configurar las credenciales de AWS
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=ASIAQU62E6EGWJSARNFO' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=UDJR1X5Fe0L1HL67wbhTuEryuCin3XsZNOuz1+zB' >> $BASH_ENV
            echo 'export AWS_DEFAULT_REGION=us-east-1' >> $BASH_ENV
            source $BASH_ENV

      # Instalar la AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli

      # Desplegar la aplicación en el bucket de S3
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./dist s3://devops-grupo-8-bucket-prod

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
