version: 2.1
environment:
  AWS_ACCESS_KEY_ID: ASIAQU62E6EGWJSARNFO
  AWS_SECRET_ACCESS_KEY: UDJR1X5Fe0L1HL67wbhTuEryuCin3XsZNOuz1+zB
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: npm install
      - run:
          name: Build app
          command: npm run build
  deploy:
    docker:
      image: node:16
    steps:
      - checkout
      - aws-s3/sync:
          from: build
          to: s3://devops-grupo-8-bucket-prod/
          arguments:
            --acl public-read
            --cache-control "max-age=31536000"
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



