version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
       # Crear una carpeta para las dependencias
      - run:
          name: Create node_modules directory
          command: mkdir -p /home/circleci/project/node_modules

      # Instalar dependencias en la carpeta local
      - run:
          name: Install dependencies
          command: npm install --prefix=/home/circleci/project
      - run:
          name: Build de la aplicacion
          command: npm run build
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
       # Crear una carpeta para las dependencias
      - run:
          name: Create node_modules directory
          command: mkdir -p /home/circleci/project/node_modules

      # Instalar dependencias en la carpeta local
      - run:
          name: Install dependencies
          command: npm install --prefix=/home/circleci/project
      - run:
          name: SonarCloud Analysis
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=src \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build