version: 2.1

setup: true

orbs:
  node: circleci/node@5.0.3
  split-config: bufferings/split-config@0.1.0 

workflows:
  generate-config:
    jobs:
      - split-config/generate-config:
          find-config-regex: .*/\.circleci/*.*\.yml
          
