version: 2.1

jobs:
  build-test-deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id ASIAQU62E6EGWJSARNFO
            aws configure set aws_secret_access_key UDJR1X5Fe0L1HL67wbhTuEryuCin3XsZNOuz1+zB
            aws configure set default.region us-east-1
            aws s3 sync build/ s3://devops-grupo-8-bucket-prod

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test-deploy