version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:14
    steps:
    - checkout
    - run: npm install
    - run:
          name: Install SonarQube Scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            export PATH=$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH
    - run:
        name: Run Tests with SonarQube Scanner
        command: sonar-scanner
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id YOUR_ACCESS_KEY
            aws configure set aws_secret_access_key YOUR_SECRET_ACCESS_KEY
            aws configure set default.region YOUR_AWS_REGION
      - run:
          name: Deploy to EKS Cluster
          command: |
            # Command to deploy to EKS cluster
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test