# This workflow is written specifically for Jam3/nextjs-boilerplate
# It uploads all contents inside the ./out/ folder generated on build:prod:static process to an AWS S3 account

name: Github Action S3 Deploy

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      S3_ORIGIN_BUCKET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@8

      - name: Permisos de acceso a Build.sh
        run: chmod +x ./.github/scripts/build.sh

      - name: Build React static site
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          CONTENTFUL_ENVIRONMENT: ${{ inputs.CONTENTFUL_ENVIRONMENT }}
          S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET }}
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v3
      
      
      - name: sync  
        uses: ./
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION
